import asyncio
import os 
from dotenv import load_dotenv
from openai import AsyncOpenAI


load_dotenv()

class ChatService:

    def __init__(self):
        api_key = os.environ["OPENROUTER_API_KEY"]

        self.client = AsyncOpenAI(
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1" 
        )

    async def ask(self,question:str) -> str:
        response = await self.client.chat.completions.create(
            model="openrouter/free",  #openrouter specific choice any free model at runtime not specific
            messages=[
                {
                    "role":"user",
                    "content":question
                }
            ]
        )

        return response.choices[0].message.content

    
    async def ask_streaming(self, question: str):
        stream = await self.client.chat.completions.create(
            model="openrouter/free",  #openrouter specific choice any free model at runtime not specific
            messages=[
                {
                    "role":"user",
                    "content":question
                }
            ],
            stream=True,
            stream_options={
                "include_usage":True
            }
        )

        async for chunk in stream:

            #Text generated by model
            if chunk.choices:
                delta = chunk.choices[0].delta

                if delta.content:
                    yield {
                        "type":"content",
                        "content":delta.content,
                    }


            #Usage information arrives in the final chunk
            if chunk.usage:
                yield {
                    "type":"usage",
                    "usage":{
                        "prompt_tokens": chunk.usage.prompt_tokens,
                        "completion_tokens": chunk.usage.completion_tokens,
                        "total_tokens": chunk.usage.total_tokens,
                    }
                }


async def main():
    chat_service = ChatService()

    query = input("Query: ")
    print("Loading.....")
    answer = await chat_service.ask(query)
  
    print(f"Answer: {answer}")



async def main_stream():
    chat_service = ChatService()

    query = input("Query: ")
    print("Loading....")

    print("Assistant: ", end="",flush=True )

    async for event in chat_service.ask_streaming(
        query
    ):
        if event["type"] == "content":
            print(event["content"],end="",flush=True)

        elif event["type"] == "usage":
            usage = event["usage"]

            print("\n")
            print("Usage: ")
            print(f"  Prompt tokens: {usage['prompt_tokens']}")
            print(f"  Completion tokens: {usage['completion_tokens']}")
            print(f"  Total tokens: {usage['total_tokens']}")
    
    print()


if __name__ == '__main__':
    asyncio.run(main_stream())
